# **A. Data Preprocessing**

In [233]:
#1. Load the dataset into your chosen machine learning environment
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.svm import SVC


df = pd.read_csv('Seeds.csv')
df

         A      P       C     LK     WK  A_Coef    LKG  target
0    15.26  14.84  0.8710  5.763  3.312   2.221  5.220       0
1    14.88  14.57  0.8811  5.554  3.333   1.018  4.956       0
2    14.29  14.09  0.9050  5.291  3.337   2.699  4.825       0
3    13.84  13.94  0.8955  5.324  3.379   2.259  4.805       0
4    16.14  14.99  0.9034  5.658  3.562   1.355  5.175       0
..     ...    ...     ...    ...    ...     ...    ...     ...
205  12.19  13.20  0.8783  5.137  2.981   3.631  4.870       2
206  11.23  12.88  0.8511  5.140  2.795   4.325  5.003       2
207  13.20  13.66  0.8883  5.236  3.232   8.315  5.056       2
208  11.84  13.21  0.8521  5.175  2.836   3.598  5.044       2
209  12.30  13.34  0.8684  5.243  2.974   5.637  5.063       2

[210 rows x 8 columns]

In [234]:
#2. GEt to know the data. HOw many records are there in teh dataset? How many columns are there? describe the first 10 and last 10 records of the dataset.
df.shape

(210, 8)

In [235]:
df.describe()

,A,P,C,LK,WK,A_Coef,LKG,target
count,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000
mean,14.847524,14.559286,0.870999,5.628533,3.258605,3.700201,5.408071,1.000000
std,2.909699,1.305959,0.023629,0.443063,0.377714,1.503557,0.491480,0.818448
min,10.590000,12.410000,0.808100,4.899000,2.630000,0.765100,4.519000,0.000000
25%,12.270000,13.450000,0.856900,5.262250,2.944000,2.561500,5.045000,0.000000
50%,14.355000,14.320000,0.873450,5.523500,3.237000,3.599000,5.223000,1.000000
75%,17.305000,15.715000,0.887775,5.979750,3.561750,4.768750,5.877000,2.000000
max,21.180000,17.250000,0.918300,6.675000,4.033000,8.456000,6.550000,2.000000

In [236]:
df.head(10)

       A      P       C     LK     WK  A_Coef    LKG  target
0  15.26  14.84  0.8710  5.763  3.312   2.221  5.220       0
1  14.88  14.57  0.8811  5.554  3.333   1.018  4.956       0
2  14.29  14.09  0.9050  5.291  3.337   2.699  4.825       0
3  13.84  13.94  0.8955  5.324  3.379   2.259  4.805       0
4  16.14  14.99  0.9034  5.658  3.562   1.355  5.175       0
5  14.38  14.21  0.8951  5.386  3.312   2.462  4.956       0
6  14.69  14.49  0.8799  5.563  3.259   3.586  5.219       0
7  14.11  14.10  0.8911  5.420  3.302   2.700  5.000       0
8  16.63  15.46  0.8747  6.053  3.465   2.040  5.877       0
9  16.44  15.25  0.8880  5.884  3.505   1.969  5.533       0

In [237]:
df.tail(10)

         A      P       C     LK     WK  A_Coef    LKG  target
200  12.38  13.44  0.8609  5.219  2.989   5.472  5.045       2
201  12.67  13.32  0.8977  4.984  3.135   2.300  4.745       2
202  11.18  12.72  0.8680  5.009  2.810   4.051  4.828       2
203  12.70  13.41  0.8874  5.183  3.091   8.456  5.000       2
204  12.37  13.47  0.8567  5.204  2.960   3.919  5.001       2
205  12.19  13.20  0.8783  5.137  2.981   3.631  4.870       2
206  11.23  12.88  0.8511  5.140  2.795   4.325  5.003       2
207  13.20  13.66  0.8883  5.236  3.232   8.315  5.056       2
208  11.84  13.21  0.8521  5.175  2.836   3.598  5.044       2
209  12.30  13.34  0.8684  5.243  2.974   5.637  5.063       2

In [238]:
#3. Perform data preprocessing steps, such as handling missing values and encoding categorical variables(If there are missing values)
df.isna()

         A      P      C     LK     WK  A_Coef    LKG  target
0    False  False  False  False  False   False  False   False
1    False  False  False  False  False   False  False   False
2    False  False  False  False  False   False  False   False
3    False  False  False  False  False   False  False   False
4    False  False  False  False  False   False  False   False
..     ...    ...    ...    ...    ...     ...    ...     ...
205  False  False  False  False  False   False  False   False
206  False  False  False  False  False   False  False   False
207  False  False  False  False  False   False  False   False
208  False  False  False  False  False   False  False   False
209  False  False  False  False  False   False  False   False

[210 rows x 8 columns]

In [239]:
df.isna().sum()

A         0
P         0
C         0
LK        0
WK        0
A_Coef    0
LKG       0
target    0
dtype: int64

In [240]:
#Since there is no NaN value in the dataset, we can proceed to the next step

In [241]:
#4. Transform categorical data into numeric(if there are)
df.dtypes

A         float64
P         float64
C         float64
LK        float64
WK        float64
A_Coef    float64
LKG       float64
target      int64
dtype: object

In [242]:
#So upon checking the dataset, its all numeric. Now we can proceed t o the next step

In [243]:
#5. Split the dataset into training and testing sets a Even:(80% Training, 20% testing)
x = df.iloc[: , :-1].values
y = df.iloc[: , -1].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [244]:
print(x_train)

[[18.95   16.42    0.8829 ...  3.755   3.368   6.148 ]
 [13.32   13.94    0.8613 ...  3.073   7.035   5.44  ]
 [16.14   14.99    0.9034 ...  3.562   1.355   5.175 ]
 ...
 [19.15   16.45    0.889  ...  3.815   3.084   6.185 ]
 [14.99   14.56    0.8883 ...  3.377   2.958   5.175 ]
 [11.27   12.97    0.8419 ...  2.763   4.309   5.    ]]

In [245]:
print(x_test)

[[13.89   14.02    0.888   5.439   3.199   3.986   4.738 ]
 [16.53   15.34    0.8823  5.875   3.467   5.532   5.88  ]
 [13.94   14.17    0.8728  5.585   3.15    2.124   5.012 ]
 [14.38   14.21    0.8951  5.386   3.312   2.462   4.956 ]
 [11.23   12.82    0.8594  5.089   2.821   7.524   4.957 ]
 [19.57   16.74    0.8779  6.384   3.772   1.472   6.273 ]
 [18.96   16.2     0.9077  6.051   3.897   4.334   5.75  ]
 [16.17   15.38    0.8588  5.762   3.387   4.286   5.703 ]
 [20.1    16.99    0.8746  6.581   3.785   1.955   6.449 ]
 [11.36   13.05    0.8382  5.175   2.755   4.048   5.263 ]
 [13.8    14.04    0.8794  5.376   3.155   1.56    4.961 ]
 [11.34   12.87    0.8596  5.053   2.849   3.347   5.003 ]
 [14.49   14.61    0.8538  5.715   3.113   4.116   5.396 ]
 [10.93   12.8     0.839   5.046   2.717   5.398   5.045 ]
 [19.31   16.59    0.8815  6.341   3.81    3.477   6.238 ]
 [18.88   16.26    0.8969  6.084   3.764   1.649   6.109 ]
 [12.11   13.27    0.8639  5.236   2.975   4.132   5.012 ]
 [17.08   15.38    0.9079  5.832   3.683   2.956   5.484 ]
 [14.34   14.37    0.8726  5.63    3.19    1.313   5.15  ]
 [14.7    14.21    0.9153  5.205   3.466   1.767   4.649 ]
 [11.02   13.      0.8189  5.325   2.701   6.735   5.163 ]
 [14.59   14.28    0.8993  5.351   3.333   4.185   4.781 ]
 [14.11   14.1     0.8911  5.42    3.302   2.7     5.    ]
 [15.03   14.77    0.8658  5.702   3.212   1.933   5.439 ]
 [18.81   16.29    0.8906  6.272   3.693   3.237   6.053 ]
 [15.56   14.89    0.8823  5.776   3.408   4.972   5.847 ]
 [18.75   16.18    0.8999  6.111   3.869   4.188   5.992 ]
 [15.99   14.89    0.9064  5.363   3.582   3.336   5.144 ]
 [11.75   13.52    0.8082  5.444   2.678   4.378   5.31  ]
 [11.56   13.31    0.8198  5.363   2.683   4.062   5.182 ]
 [16.77   15.62    0.8638  5.927   3.438   4.92    5.795 ]
 [10.79   12.93    0.8107  5.317   2.648   5.462   5.194 ]
 [15.6    15.11    0.858   5.832   3.286   2.725   5.752 ]
 [16.84   15.67    0.8623  5.998   3.484   4.675   5.877 ]
 [10.91   12.8     0.8372  5.088   2.675   4.179   4.956 ]
 [11.21   13.13    0.8167  5.279   2.687   6.169   5.275 ]
 [11.26   13.01    0.8355  5.186   2.71    5.335   5.092 ]
 [18.89   16.23    0.9008  6.227   3.769   3.639   5.966 ]
 [13.99   13.83    0.9183  5.119   3.383   5.234   4.781 ]
 [15.38   14.66    0.899   5.477   3.465   3.6     5.439 ]
 [11.27   12.86    0.8563  5.091   2.804   3.985   5.001 ]
 [15.88   14.9     0.8988  5.618   3.507   0.7651  5.091 ]]

In [246]:
print(y_test)

[0 1 0 0 2 1 1 1 1 2 0 2 0 2 1 1 2 0 0 0 2 0 0 0 1 1 1 1 2 2 1 2 1 1 2 2 2
 1 0 1 2 0]

# **B. Model Building**

In [247]:
#6. Use naive bayes with gaussian as the classifier. what is the accuracy score of the model
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [248]:
print(x_train)

[[18.95   16.42    0.8829 ...  3.755   3.368   6.148 ]
 [13.32   13.94    0.8613 ...  3.073   7.035   5.44  ]
 [16.14   14.99    0.9034 ...  3.562   1.355   5.175 ]
 ...
 [19.15   16.45    0.889  ...  3.815   3.084   6.185 ]
 [14.99   14.56    0.8883 ...  3.377   2.958   5.175 ]
 [11.27   12.97    0.8419 ...  2.763   4.309   5.    ]]

In [249]:
print(x_test)

[[13.89   14.02    0.888   5.439   3.199   3.986   4.738 ]
 [16.53   15.34    0.8823  5.875   3.467   5.532   5.88  ]
 [13.94   14.17    0.8728  5.585   3.15    2.124   5.012 ]
 [14.38   14.21    0.8951  5.386   3.312   2.462   4.956 ]
 [11.23   12.82    0.8594  5.089   2.821   7.524   4.957 ]
 [19.57   16.74    0.8779  6.384   3.772   1.472   6.273 ]
 [18.96   16.2     0.9077  6.051   3.897   4.334   5.75  ]
 [16.17   15.38    0.8588  5.762   3.387   4.286   5.703 ]
 [20.1    16.99    0.8746  6.581   3.785   1.955   6.449 ]
 [11.36   13.05    0.8382  5.175   2.755   4.048   5.263 ]
 [13.8    14.04    0.8794  5.376   3.155   1.56    4.961 ]
 [11.34   12.87    0.8596  5.053   2.849   3.347   5.003 ]
 [14.49   14.61    0.8538  5.715   3.113   4.116   5.396 ]
 [10.93   12.8     0.839   5.046   2.717   5.398   5.045 ]
 [19.31   16.59    0.8815  6.341   3.81    3.477   6.238 ]
 [18.88   16.26    0.8969  6.084   3.764   1.649   6.109 ]
 [12.11   13.27    0.8639  5.236   2.975   4.132   5.012 ]
 [17.08   15.38    0.9079  5.832   3.683   2.956   5.484 ]
 [14.34   14.37    0.8726  5.63    3.19    1.313   5.15  ]
 [14.7    14.21    0.9153  5.205   3.466   1.767   4.649 ]
 [11.02   13.      0.8189  5.325   2.701   6.735   5.163 ]
 [14.59   14.28    0.8993  5.351   3.333   4.185   4.781 ]
 [14.11   14.1     0.8911  5.42    3.302   2.7     5.    ]
 [15.03   14.77    0.8658  5.702   3.212   1.933   5.439 ]
 [18.81   16.29    0.8906  6.272   3.693   3.237   6.053 ]
 [15.56   14.89    0.8823  5.776   3.408   4.972   5.847 ]
 [18.75   16.18    0.8999  6.111   3.869   4.188   5.992 ]
 [15.99   14.89    0.9064  5.363   3.582   3.336   5.144 ]
 [11.75   13.52    0.8082  5.444   2.678   4.378   5.31  ]
 [11.56   13.31    0.8198  5.363   2.683   4.062   5.182 ]
 [16.77   15.62    0.8638  5.927   3.438   4.92    5.795 ]
 [10.79   12.93    0.8107  5.317   2.648   5.462   5.194 ]
 [15.6    15.11    0.858   5.832   3.286   2.725   5.752 ]
 [16.84   15.67    0.8623  5.998   3.484   4.675   5.877 ]
 [10.91   12.8     0.8372  5.088   2.675   4.179   4.956 ]
 [11.21   13.13    0.8167  5.279   2.687   6.169   5.275 ]
 [11.26   13.01    0.8355  5.186   2.71    5.335   5.092 ]
 [18.89   16.23    0.9008  6.227   3.769   3.639   5.966 ]
 [13.99   13.83    0.9183  5.119   3.383   5.234   4.781 ]
 [15.38   14.66    0.899   5.477   3.465   3.6     5.439 ]
 [11.27   12.86    0.8563  5.091   2.804   3.985   5.001 ]
 [15.88   14.9     0.8988  5.618   3.507   0.7651  5.091 ]]

In [250]:
#Predicting the test set results
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [2 2]
 [0 0]
 [2 2]
 [0 0]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 0]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [0 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [0 1]
 [2 2]
 [0 0]]

In [251]:
#6. Use naive bayes with gaussian as the classifier. what is the accuracy score of the model

cm_labeled = pd.DataFrame(cm, index=['Kama', 'Rosa', 'Canadian'], columns=['Kama', 'Rosa', 'Canadian'])
print(cm_labeled)

          Kama  Rosa  Canadian
Kama        12     1         0
Rosa         5    11         0
Canadian     0     0        13

In [252]:

# Print accuracy score
print("Accuracy Score Of The Model Using Naive Bayes:", accuracy_score(y_test, y_pred))

Accuracy Score Of The Model Using Naive Bayes: 0.8571428571428571

In [253]:
#7. USe SVM with linear as the kernel trick. What is the accuracy score of the model?

svm_classifier = SVC(kernel='linear', random_state=0)

In [254]:
# Fitting the classifier to the training data
svm_classifier.fit(x_train, y_train)

# Make predictions on the test data
y_pred_svm = svm_classifier.predict(x_test)

# Calculate accuracy score
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print("Accuracy Score Of The Model Using  SVM (Linear Kernel):", accuracy_svm)

Accuracy Score Of The Model Using  SVM (Linear Kernel): 0.9047619047619048

In [255]:
# svm confusion matrix
cm_svm = confusion_matrix(y_test, y_pred_svm)
cm_svm_labeled = pd.DataFrame(cm_svm, index=['Kama', 'Rosa', 'Canadian'], columns=['Kama', 'Rosa', 'Canadian'])
print(cm_svm_labeled)

          Kama  Rosa  Canadian
Kama        12     1         0
Rosa         3    13         0
Canadian     0     0        13

# **C. Model Evaluation**

# Naive Bayes

In [256]:
#8. Create Confusion Matrix and classification report

# Confusion Matrix for Naive Bayes
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix (Naive Bayes):\n", cm)

# Classification Report for Naive Bayes
print("\nClassification Report (Naive Bayes):\n", classification_report(y_test, y_pred))

Confusion Matrix (Naive Bayes):
 [[12  1  0]
 [ 5 11  0]
 [ 0  0 13]]

Classification Report (Naive Bayes):
               precision    recall  f1-score   support

           0       0.71      0.92      0.80        13
           1       0.92      0.69      0.79        16
           2       1.00      1.00      1.00        13

    accuracy                           0.86        42
   macro avg       0.87      0.87      0.86        42
weighted avg       0.88      0.86      0.86        42

# SVM

In [257]:
# Confusion Matrix for SVM
cm_svm = confusion_matrix(y_test, y_pred_svm)
print("\nConfusion Matrix (SVM - Linear Kernel):\n", cm_svm)

# Classification Report for SVM
print("\nClassification Report (SVM - Linear Kernel):\n", classification_report(y_test, y_pred_svm))

Confusion Matrix (SVM - Linear Kernel):
 [[12  1  0]
 [ 3 13  0]
 [ 0  0 13]]

Classification Report (SVM - Linear Kernel):
               precision    recall  f1-score   support

           0       0.80      0.92      0.86        13
           1       0.93      0.81      0.87        16
           2       1.00      1.00      1.00        13

    accuracy                           0.90        42
   macro avg       0.91      0.91      0.91        42
weighted avg       0.91      0.90      0.90        42

In [258]:
#9. Evaluate the models based on item 8, in paragraph format

# Based on the confusion matrix and classification report, both Naive Bayes and SVM (linear kernel) models show good performance in classifying the seed varieties. However, the SVM model slightly outperforms Naive Bayes with a higher accuracy score. Both models demonstrate strong precision and recall for all three seed varieties (Kama, Rosa, and Canadian), indicating their ability to correctly identify and classify the different types of seeds. Overall, both models are effective for this classification task, but SVM with a linear kernel provides a slightly better performance.