In [ ]:
# 1. Load the "IRIS2.csv" dataset into your chosen machine learning environment in Google Colab

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('IRIS2.csv')

df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
#2. Perform data preprocessing steps, such as handling missing values and encoding categorical variable (if there are missing values)

In [ ]:

missing_values = df.isnull().sum()

if missing_values.any():

  df = df.dropna()
  df = df.fillna(df.mean())

categorical_columns = df.select_dtypes(include=['object']).columns
for column in categorical_columns:
  df[column] = pd.Categorical(df[column]).codes
print(missing_values)
df

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [ ]:
#3.Split the dataset into training and testing sets for 80% traing, 20% testing

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop('species', axis=1)
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train

     sepal_length  sepal_width  petal_length  petal_width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]

In [ ]:
#4. Build an SVM classification model using the training data

In [ ]:

model = SVC(kernel='linear')
model.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
#5.Use kernel parameter RBF

In [ ]:

model = SVC(kernel='rbf')
model.fit(X_train, y_train)

SVC()

In [ ]:
# 6.What is the result or score of the model?

In [ ]:
print("Score with RBF kernel:", model.score(X_test, y_test))

Score with RBF kernel: 1.0

In [ ]:
# 7.Use kernel parameter Linear.

In [ ]:
model = SVC(kernel='linear')
model.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
#8.What is the result or score of the model?

In [ ]:
print("Score with Linear kernel:", model.score(X_test, y_test))

Score with Linear kernel: 1.0

In [ ]:
# 9.use kernel parameter polynomial.

In [ ]:
model = SVC(kernel='poly')
model.fit(X_train, y_train)
print("Score with Polynomial kernel:", model.score(X_test, y_test))

Score with Polynomial kernel: 1.0

In [ ]:
# 10.what is the result or score of the model?

In [ ]:
print("Score with Polynomial kernel:", model.score(X_test, y_test))

Score with Polynomial kernel: 1.0

In [ ]:
# 11.which among the kernel parameters is the most accurate?Justify you answer

In [ ]:
best_kernel = None
best_score = 0
for kernel in ['linear', 'rbf', 'poly']:
  model = SVC(kernel=kernel)
  model.fit(X_train, y_train)
  score = model.score(X_test, y_test)
  if score > best_score:
    best_kernel = kernel
    best_score = score

print("Most accurate kernel:", best_kernel, "with score:", best_score)

Most accurate kernel: linear with score: 1.0